name: Node.js CI

on: push

jobs:
  test:
    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ $matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
